//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodInventory
    {
        public int id { get; set; }
        public string DonorName { get; set; }
        public string DonarAddress { get; set; }
        public Nullable<int> DonorPhone { get; set; }
        public string BloodType { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string CollectLocation { get; set; }
        public string StaffName { get; set; }
    }
}
