//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Age { get; set; }
        public string BloodType { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> LastDonationDate { get; set; }
        public string other { get; set; }
    }
}
